/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as mainLayoutRouteImport } from './routes/(main)/_layout'
import { Route as mainLayoutIndexRouteImport } from './routes/(main)/_layout/index'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as mainLayoutContactsRouteImport } from './routes/(main)/_layout/contacts'
import { Route as mainLayoutAboutRouteImport } from './routes/(main)/_layout/about'
import { Route as mainLayoutShopIndexRouteImport } from './routes/(main)/_layout/shop/index'
import { Route as mainLayoutBlogIndexRouteImport } from './routes/(main)/_layout/blog/index'
import { Route as mainLayoutShopProductsRouteImport } from './routes/(main)/_layout/shop/products'
import { Route as mainLayoutShopProductIdRouteImport } from './routes/(main)/_layout/shop/$productId'
import { Route as mainLayoutBlogPostIdRouteImport } from './routes/(main)/_layout/blog/$postId'

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutRoute = mainLayoutRouteImport.update({
  id: '/(main)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutIndexRoute = mainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const mainLayoutContactsRoute = mainLayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutAboutRoute = mainLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutShopIndexRoute = mainLayoutShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutBlogIndexRoute = mainLayoutBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutShopProductsRoute = mainLayoutShopProductsRouteImport.update({
  id: '/shop/products',
  path: '/shop/products',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutShopProductIdRoute = mainLayoutShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutBlogPostIdRoute = mainLayoutBlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/about': typeof mainLayoutAboutRoute
  '/contacts': typeof mainLayoutContactsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/': typeof mainLayoutIndexRoute
  '/blog/$postId': typeof mainLayoutBlogPostIdRoute
  '/shop/$productId': typeof mainLayoutShopProductIdRoute
  '/shop/products': typeof mainLayoutShopProductsRoute
  '/blog/': typeof mainLayoutBlogIndexRoute
  '/shop/': typeof mainLayoutShopIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminIndexRoute
  '/about': typeof mainLayoutAboutRoute
  '/contacts': typeof mainLayoutContactsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/': typeof mainLayoutIndexRoute
  '/blog/$postId': typeof mainLayoutBlogPostIdRoute
  '/shop/$productId': typeof mainLayoutShopProductIdRoute
  '/shop/products': typeof mainLayoutShopProductsRoute
  '/blog': typeof mainLayoutBlogIndexRoute
  '/shop': typeof mainLayoutShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/_layout': typeof mainLayoutRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/(main)/_layout/about': typeof mainLayoutAboutRoute
  '/(main)/_layout/contacts': typeof mainLayoutContactsRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/(main)/_layout/': typeof mainLayoutIndexRoute
  '/(main)/_layout/blog/$postId': typeof mainLayoutBlogPostIdRoute
  '/(main)/_layout/shop/$productId': typeof mainLayoutShopProductIdRoute
  '/(main)/_layout/shop/products': typeof mainLayoutShopProductsRoute
  '/(main)/_layout/blog/': typeof mainLayoutBlogIndexRoute
  '/(main)/_layout/shop/': typeof mainLayoutShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/'
    | '/about'
    | '/contacts'
    | '/admin/dashboard'
    | '/admin/users'
    | '/'
    | '/blog/$postId'
    | '/shop/$productId'
    | '/shop/products'
    | '/blog/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/contacts'
    | '/admin/dashboard'
    | '/admin/users'
    | '/'
    | '/blog/$postId'
    | '/shop/$productId'
    | '/shop/products'
    | '/blog'
    | '/shop'
  id:
    | '__root__'
    | '/(main)/_layout'
    | '/admin/_layout'
    | '/admin/'
    | '/(main)/_layout/about'
    | '/(main)/_layout/contacts'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/users'
    | '/(main)/_layout/'
    | '/(main)/_layout/blog/$postId'
    | '/(main)/_layout/shop/$productId'
    | '/(main)/_layout/shop/products'
    | '/(main)/_layout/blog/'
    | '/(main)/_layout/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout': {
      id: '/(main)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout/': {
      id: '/(main)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainLayoutIndexRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/(main)/_layout/contacts': {
      id: '/(main)/_layout/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof mainLayoutContactsRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/about': {
      id: '/(main)/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainLayoutAboutRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/shop/': {
      id: '/(main)/_layout/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof mainLayoutShopIndexRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/blog/': {
      id: '/(main)/_layout/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof mainLayoutBlogIndexRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/shop/products': {
      id: '/(main)/_layout/shop/products'
      path: '/shop/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof mainLayoutShopProductsRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/shop/$productId': {
      id: '/(main)/_layout/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof mainLayoutShopProductIdRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/blog/$postId': {
      id: '/(main)/_layout/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof mainLayoutBlogPostIdRouteImport
      parentRoute: typeof mainLayoutRoute
    }
  }
}

interface mainLayoutRouteChildren {
  mainLayoutAboutRoute: typeof mainLayoutAboutRoute
  mainLayoutContactsRoute: typeof mainLayoutContactsRoute
  mainLayoutIndexRoute: typeof mainLayoutIndexRoute
  mainLayoutBlogPostIdRoute: typeof mainLayoutBlogPostIdRoute
  mainLayoutShopProductIdRoute: typeof mainLayoutShopProductIdRoute
  mainLayoutShopProductsRoute: typeof mainLayoutShopProductsRoute
  mainLayoutBlogIndexRoute: typeof mainLayoutBlogIndexRoute
  mainLayoutShopIndexRoute: typeof mainLayoutShopIndexRoute
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  mainLayoutAboutRoute: mainLayoutAboutRoute,
  mainLayoutContactsRoute: mainLayoutContactsRoute,
  mainLayoutIndexRoute: mainLayoutIndexRoute,
  mainLayoutBlogPostIdRoute: mainLayoutBlogPostIdRoute,
  mainLayoutShopProductIdRoute: mainLayoutShopProductIdRoute,
  mainLayoutShopProductsRoute: mainLayoutShopProductsRoute,
  mainLayoutBlogIndexRoute: mainLayoutBlogIndexRoute,
  mainLayoutShopIndexRoute: mainLayoutShopIndexRoute,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainLayoutRoute: mainLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
